In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# model.forward 가져오기
def forward(news_encoder, user_encoder, batch):
    # encode candidate news
    candidate_news_vector = news_encoder(batch["c_title"])
    
    # encode history 
    clicked_news_vector = news_encoder(batch["h_title"])
    # encode user
    user_vector = user_encoder(clicked_news_vector)
    # compute scores for each candidate news
    clicks_score = torch.bmm(
        candidate_news_vector,
        user_vector.unsqueeze(dim=-1)).squeeze(dim=-1)
    
    return clicks_score

In [ ]:
print(torch.tensor([3.1, 2.4, 5.5, 6.6, 7.7]))
print(torch.tensor([3.1, 2.4, 5.5, 6.6, 7.7]).size())
print(torch.tensor([3.1, 2.4, 5.5, 6.6, 7.7]).shape)
print(F.dropout(torch.tensor([3.1, 2.4, 5.5, 6.6, 7.7]), p=0.5, training=True))

tensor([3.1000, 2.4000, 5.5000, 6.6000, 7.7000])
torch.Size([5])
torch.Size([5])
tensor([ 6.2000,  0.0000, 11.0000,  0.0000, 15.4000])


In [ ]:
word_embedding = nn.Embedding.from_pretrained(
    model_manager.pretrained_word_embedding,
    freeze=model_manager.config.freeze_word_embeddings,
    padding_idx=0)

In [ ]:
word_embedding(torch.tensor([0]))

In [ ]:
news_encoder = model_manager.model.news_encoder
user_encoder = model_manager.model.user_encoder

forward(news_encoder, user_encoder, batch_data)

tensor([[  2.4618,   0.8308, -17.1481, -12.9286, -29.9921,  -8.5086,  -9.3151,
         -24.2817,  21.9645,  -3.8677,  -8.9765,   0.3124, -12.9673, -12.2673,
         -11.0726, -10.6365,   0.1682,   7.6042,  -6.0632, -13.7158,  14.3706,
          21.6398,  13.3914,   3.2512,  -8.1647,  -5.4390,   4.4983,  -0.6794]],
       device='cuda:0', grad_fn=<SqueezeBackward1>)

In [ ]:
# encode candidate news
candidate_news_vector = news_encoder(batch_data["c_title"])

# encode history 
clicked_news_vector = news_encoder(batch_data["h_title"])
# encode user
user_vector = user_encoder(clicked_news_vector)

clicks_score = torch.bmm(
        candidate_news_vector,
        user_vector.unsqueeze(dim=-1)).squeeze(dim=-1)

In [ ]:
print(candidate_news_vector.shape)
print(clicked_news_vector.shape)
print(user_vector.shape)
print(user_vector.unsqueeze(dim=-1).shape)
print(torch.bmm(
        candidate_news_vector,
        user_vector.unsqueeze(dim=-1)).shape)
print(clicks_score.shape)

torch.Size([1, 28, 300])
torch.Size([1, 50, 300])
torch.Size([1, 300])
torch.Size([1, 300, 1])
torch.Size([1, 28, 1])
torch.Size([1, 28])


In [ ]:
torch.bmm(
        candidate_news_vector,
        user_vector.unsqueeze(dim=-1)).squeeze(-1)

tensor([[  2.4618,   0.8308, -17.1481, -12.9286, -29.9921,  -8.5086,  -9.3151,
         -24.2817,  21.9645,  -3.8677,  -8.9765,   0.3124, -12.9673, -12.2673,
         -11.0726, -10.6365,   0.1682,   7.6042,  -6.0632, -13.7158,  14.3706,
          21.6398,  13.3914,   3.2512,  -8.1647,  -5.4390,   4.4983,  -0.6794]],
       device='cuda:0', grad_fn=<SqueezeBackward1>)